### ISSUE TITLE
Django Guardian compatibility

### ISSUE THREAD

**Issue by LilithWittmann** [serioeseGmbH/serious-django-permissions#10]
Currently I'm trying to use Permissions from django-permissions together with djano guardian and facing some issues:

I would like to use guardian functions like assign_perm to add permissions for specific objects to groups of users:
```python
assign_perm(MyPermission, group, app)
```
this fails first because guardian tries to use the str representation of the Permission here (because it assumes that our Permission object is a string if it is not a Permission object). This should be pretty easy to fix, by adding a string representation. (see https://github.com/django-guardian/django-guardian/blob/8382df9362dc80059864124e93d90418ae44637c/guardian/shortcuts.py#L94)

But if I use Permission.codename instead of Permission it still fails because then django-guardian tries to use the codename of the permission and the content type of the object to lookup the permission in the django Permissions table (see: https://github.com/django-guardian/django-guardian/blob/devel/guardian/managers.py#L34)

I have no idea how to fix this.

**Edit:** The 2nd issue only exists if the permission assigned to the object is a global permission or a permission that is not related to the model of the object. (what sometimes is the case if we continue to use our permissions like we do right now.)

**Comment by cobalamin** [comment]
Should be closed in https://github.com/serioeseGmbH/serious-django-permissions/commit/90ba92387068f21f4c3fb4c77879f22b9c74a7ae -- but I'm unsure if I've covered all bases. Let me know if it works for your use cases. You can definitely do `.assign_perm(...)` like above, and also check the permissions via `.has_perm`: See [the tests](https://github.com/serioeseGmbH/serious-django-permissions/commit/90ba92387068f21f4c3fb4c77879f22b9c74a7ae#diff-db0878cacd013dc827e5b0264b477dfcR265).

**Comment by cobalamin** [comment]
(build is currently failing because I haven't bumped the version. Should've put this on a feature branch, but oh well, too late. I'd prefer not pushing a new version until you're sure this works for you.)

**Comment by LilithWittmann** [comment]
Works 🎉 🎉 🎉

**Comment by cobalamin** [comment]
Cool :100:
