### ISSUE TITLE
Simplify usage of `@permission_required()` decorator

### ISSUE THREAD

**Issue by seblat** [serioeseGmbH/serious-django-permissions#4]
When using the [`@permission_required()` decorator](https://docs.djangoproject.com/en/2.1/topics/auth/default/#the-permission-required-decorator) on a view, the permssion is pased to the decorator in a  `<app label>.<permission codename>` format. E.g.: `@permission_required('pollsapp.can_vote')`

Using serious-django-permissions you would expect the permission to be passed via the `.codename` property. E.g.: `@permission_required('test_app.RestrictedModelPermission.codename')`. Yet this way the decorator does not recognize the permission.

The permission codename has to be passed explicitly. Eg.: `@permission_required('test_app.restricted_model')` 
with `RestrictedModelPermission.codename = "restricted_model"`

I guess passing the permission via `@permission_required('test_app.RestrictedModelPermission.codename')` or even `@permission_required('test_app.RestrictedModelPermission')` would simplify using the decorator with serious-django-permissions. @cobalamin any thoughts on that?

**Comment by cobalamin** [comment]
Have you tried explicitly importing the permission (as with usual permission checks) and referencing it not as a string but as a value? e.g.:

```python
from .permissions import RestrictedModelPermission

@permission_required(RestrictedModelPermission)
def my_view(...):
    ...
```

Skimming over the Django source for this decorator, I think this should just work.

**Comment by seblat** [comment]
> Have you tried explicitly importing the permission (as with usual permission checks) and referencing it not as a string but as a value?

Yes, with:

```
from django.http import HttpResponse
from django.contrib.auth.decorators import permission_required

from .permissions import RestrictedModelPermission


@permission_required(RestrictedModelPermission)
def restricted_view(request):
    return HttpResponse("You've accessed a restricted_view")
```

Yet, this results in `TypeError: 'PermissionMetaclass' object is not iterable`

**Comment by cobalamin** [comment]
I fixed that in a bit of a ridiculous way: `PermissionMetaclass` is now iterable, and returns an iterator that only contains `PermissionMetaclass` itself once. Seems to work for the test cases. The reason this works then is that it (implicitly) allows a single Permission to be passed and treated like a list. The code for the decorator inside Django always internally requires a list of permissions to check, but also allows passing exactly one string, which is then noticed and converted to a list containing only that string. It doesn't do that same conversion for our Permissions though, because those are clearly not strings.

**Comment by seblat** [comment]
After the [fix](https://github.com/serioeseGmbH/serious-django-permissions/pull/3/commits/70394130ae2c4029a6298e0f9e9bdcebaede2e02), the decorator can now be called with the imported permissions class. E.g.:

```
from .permissions import RestrictedModelPermission

@permission_required(RestrictedModelPermission)
def my_view(...):
```
