### ISSUE TITLE
Make model attribute for Permissions optional

### ISSUE THREAD

**Issue by LilithWittmann** [serioeseGmbH/serious-django-permissions#6]
Currently you need to provide a ```model```attribute inside a Permission class. This attribute can be empty or none, if a permission should be public. 

But if the model attribute is not defined there is an error:

```bash
======================================================================
ERROR: test_application_creation_by_admin (applications.tests.ApplicationAdminServiceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lilithwittmann/code/ressource_management/applications/tests.py", line 12, in setUp
    create_permissions.Command().handle()
  File "/Users/lilithwittmann/code/.virtualenvs/ressource_management-h_07sZrZ/lib/python3.7/site-packages/serious_django_permissions/management/commands/create_permissions.py", line 29, in handle
    perm, created_at = obj.get_or_create()
  File "/Users/lilithwittmann/code/.virtualenvs/ressource_management-h_07sZrZ/lib/python3.7/site-packages/serious_django_permissions/permissions.py", line 55, in get_or_create
    if cls.model is not None:
AttributeError: type object 'ApplicationAdminPermission' has no attribute 'model'

----------------------------------------------------------------------
Ran 1 test in 0.007s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

It would be nice if we just could check if the model attribute exists beforehand so it don't has to be set to None explicitly.

**Comment by cobalamin** [comment]
This was done intentionally to avoid creating global permissions just because someone forgot to specify a model at first, since global permissions are created in a way that's quite "extra". Also, I generally prefer explicit over implicit.

**Comment by cobalamin** [comment]
(I say this was intentional, but apparently forgot to include this in the verification that's done on the metaclass :sweat_smile: )

**Comment by LilithWittmann** [comment]
OK this makes sense, but then a verification and a more explicit message would be awesome. ^^

**Comment by cobalamin** [comment]
Yeah, that's true. Will do ASAP.
