### ISSUE TITLE
Allow a model instance as model attribute inside a permission

### ISSUE THREAD

**Issue by LilithWittmann** [serioeseGmbH/serious-django-permissions#7]
Currently the model attribute of a Permission has to be a string. It would be nicer/easier to debug if this could be a model class.

**Comment by cobalamin** [comment]
I think when first implementing this, the issue was circular imports (or apps not being "ready", i.e. loaded, at the right time). Are we 100% sure we want to force users to never be able to use permissions inside models?

**Comment by LilithWittmann** [comment]
Maybe we should allow both.

**Comment by LilithWittmann** [comment]
Maybe we should allow both.

**Comment by cobalamin** [comment]
Alright, I'll look into it soon.

**Comment by cobalamin** [comment]
added in https://github.com/serioeseGmbH/serious-django-permissions/commit/51a0632169c616a7b0664d3bd88c0eaaed69a819 .
