### ISSUE TITLE
.has_perm always fails on global permissions

### ISSUE THREAD

**Issue by LilithWittmann** [serioeseGmbH/serious-django-permissions#8]
When I try to create a permission with  `model = None` the permission check via user.has_perm will always return False even if the user has the permission.

**Comment by cobalamin** [comment]
Not sure what you mean, how does this test pass then? https://github.com/serioeseGmbH/serious-django-permissions/blob/master/test_project/test_app/tests.py#L200-L201

**Comment by LilithWittmann** [comment]
OK this happens only if the permission is given to the user via a Group. (see https://github.com/serioeseGmbH/serious-django-permissions/commit/bcd2dd208b6c0cacea67128c0dab0c22fed8eb82)

**Comment by cobalamin** [comment]
Alright, that helped to track it down. :) Fixed in https://github.com/serioeseGmbH/serious-django-permissions/commit/bb66b0e579f332c1497b10b0cc4532c5186d5183
